### ISSUE TITLE
faker generates unsupported timezones

### ISSUE THREAD

**Issue by rijan0101** [fzaninotto/Faker#1010]
faker generates unsupported timezones

**Comment by fzaninotto** [comment]
Can you be more specific? Which timezone did it generate that doesn't exist?

**Comment by CyrilMazur** [comment]
I have the same issue, these two timezones returned by Faker make `IntlDateFormatter()` crash: Europe/Ulyanovsk and America/Fort_Nelson. There's maybe more, I haven't checked them all.

**Comment by CyrilMazur** [comment]
Additional info. I noticed some timezones made `IntlDateFormatter()` crash on my laptop but not in my CI instance. I think what matters is the ICU Data version, which depends on what system you're using. Debian 7 and 8 provide pretty old versions of the ICU data for instance. One solution would be to decrease Faker's  list of timezones to just the "safe" ones, ie those who are present in ICU for quite a long time.

**Comment by curry684** [comment]
> those who are present in ICU for quite a long time

It's not exactly a list with daily changes, and taking an old copy is just as likely to trigger results that were renamed or dropped since then as a new list has the other way around.

However the issue makes no sense, as the timezone generator was [implemented 5 years ago and works directly on PHP's internal list of supported timezones](https://github.com/fzaninotto/Faker/blame/3860fbe35dff991f39640a38f51807e2594c9783/src/Faker/Provider/DateTime.php#L284). There is simply no way it can generate an invalid timezone, *unless* you're using it in communication with other tooling than PHP itself, which is outside the scope and responsibility of Faker.

**Comment by shadowhand** [comment]
Same problem here.

**Comment by fzaninotto** [comment]
I'm afraid this is a PHP bug, since Faker relies on `\DateTimeZone::listIdentifiers()` to get a list of valid timezones. Please open an issue in the PHP bug tracker instead.
