### ISSUE TITLE
Teach regexify formatter about [\d]{3} syntax

### ISSUE THREAD

**Issue by meglio** [fzaninotto/Faker#1100]
Currently, this will not work with `regixify`:

`[\d]{3}`

However, this will do:

`\d{3}`

This is a case where an improvement is possible.

**Comment by fzaninotto** [comment]
Yeah, as the phpDoc says:

```php
    /*
     * Only supports a small subset of the regex syntax. For instance,
     * unicode, negated classes, unbouned ranges, subpatterns, back references,
     * assertions, recursive patterns, and comments are not supported. Escaping
     * support is extremely fragile.
     *
     * This method is also VERY slow. Use it only when no other formatter
     * can generate the fake data you want. For instance, prefer calling
     * `$faker->email` rather than `regexify` with the previous regular
```

We won't spend time trying to support more regular expression syntax in `regexify`.

**Comment by meglio** [comment]
Closing an issue straight away does not look like a good reaction to
people's effort in contribingte to your project.

I created this ticket just because it is a simple case and will not need
any sophisticated code.

You could add a "pr-welcome" label and leave it open for community to
decide wether to contribute.

**Comment by fzaninotto** [comment]
Sorry if this sounds rude, it's not intended. 

If you feel like opening a PR, please do so - don't ask for my blessing with an issue first.

In my experience, feature request issues are useless. This is a not a project where random devs from around the world ask for something and someone else (me) develop it in their free time for pleasure.

Also, keep in mind that, when dealing with a 9,000+ stars project, lots of contributors offer some code... and then leave. The result, is that **I** have to maintain that code. That's why I can be picky sometimes.
