### ISSUE TITLE
[he_IL] email username transliteration

### ISSUE THREAD

**Issue by eodin** [fzaninotto/Faker#1263]
I'm using Faker to test localization issues in my application and I've found the bug in [he_IL] locale.
```php
$faker = Faker\Factory::create( 'he_IL' );

$client['first_name'] = $faker->firstName;   // result is 'פורת'
$client['last_name']  = $faker->lastName;   // result is 'תאומים'
$client['email']      = $faker->unique()->safeEmail; // result is '.@example.net'
```
When I'm using this code for ModelFactory I'm getting email unique error. 
```
  [PDOException (23000)]
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '.@example.net' for key 'users_email_unique'
```

I haven't php_intl ext in my docker container and seems `static::toAscii($string)` knows nothing about [he_IL]

**Comment by Newman101** [comment]
Hi. 

I checked through the Hebrew generator and noticed that there is no e-mail method in the locale. In the absence of it, Faker seems to use the generic e-mail addresses. Maybe this should be added in order to make the structure consistent. 

I will submit a pull request in order to fix the transliteration.

**Comment by pimjansen** [comment]
I will close this issue since it seems to no longer be relevant. I tried it with code above and following data is returned:

```
Array
(
    [first_name] => רימון
    [last_name] => אייגש
    [email] => spryr.qrlybk@example.org
)
```
