### ISSUE TITLE
realText really slow, maybe we could implements a faster and simpler version?

### ISSUE THREAD

**Issue by kenger** [fzaninotto/Faker#1684]
Hi,

I'm using realText to generate 9 iterations ( in 9 languages ) of

        $faker = \Faker\Factory::create($langData['locale']);
        $data['x'] = $faker->realText( 80 );
        $data['y'] = $faker->realText( 150 );

and the code take ~760ms to execute.

There is some kinds of faster approach? I dont really need a random text, only some localized text.  There is some kind of fastRealText( 150 ) who just take 150 characters of the existing localized text and return it?

Thanks

**Comment by Dzhuneyt** [comment]
Have you tried experimenting with the second parameter that the function accepts?

`public function realText($maxNbChars = 200, $indexSize = 2)`

It accepts a value between 1 and 5. According to the documentation:

> Determines how many words are considered for the generation of the next word. The minimum is 1, and it produces the higher level of randomness, although the generated text usually doesn't make sense. Higher index sizes (up to 5) produce more correct text, at the price of less randomness.

**Comment by pimjansen** [comment]
I tried above use case with 7 different locales on which my system took 0.14309501647949 seconds to generate. So there is not much to change here. What @Dzhuneyt says is valid, the higher the indentsize the better the text but the slower it will be

If you dont care about the actual textual output and you just want something that looks like text you can always use the `text` method which does it in `0.015255928039551 seconds`

I will close this issue since it is not really a bug in faker
