### ISSUE TITLE
Lorem Pixel SSL error

### ISSUE THREAD

**Issue by blorange2** [fzaninotto/Faker#1712]
The `Image` provider uses Lorem Pixel with the domain `https://lorempixel.com/`, it would seem that the SSL for that site is invalid.

So, when you call the method it just returns `false`

Would it be better to update the URL or use a different provider?

**Comment by xiaohuilam** [comment]
And it seems down now.

**Comment by t00nami** [comment]
> And it seems down now.

Yes, It's down.

**Comment by xiaohuilam** [comment]
https://github.com/Marak/faker.js/issues/641

**Comment by jnowland** [comment]
The error is due to the https url getting forwarded to HTTP.

Faker URL Generated:
`https://lorempixel.com/900/600/city?20118`

Loem pixel do support HTTPS images however it is in the following format:
`https://lorempixel.com/900/600/city/?20118`

Note the '/' after the category. This needs to be added to:
https://github.com/Marak/faker.js/blob/master/lib/image_providers/lorempixel.js#L45

**Comment by pimjansen** [comment]
The idea is to remove the image generation complete from the Faker core and to work with a provider here. So i will close this issue for now since the existing cert is valid again.
