### ISSUE TITLE
HTML ipsum generator 

### ISSUE THREAD

**Issue by Petah** [fzaninotto/Faker#203]
It would be great if there was a HTML ipsum generator like: http://loripsum.net/

**Comment by iBasit** [comment]
+1

**Comment by dmyers** [comment]
It might be interesting to fake with tons of random HTML elements. My use case is to test an email parser with different levels of nesting and everything.

**Comment by fzaninotto** [comment]
Work is ongoing in #514.

I was recently thinking about another approach: a simple web client combined with a list of 500 URLs based on Alexa's top websites ranking. The randomization part is to determine which URL needs to be fetched.

Pros:
- Real HTML
- Many use cases
- Representative of what you will find on the web

Cons:
- Complete HTML pages vs segments
- Slow (although the approach started in #514 may not be faster)
- requires access to the web
- not really seedable, since it's based on an external datasource (alternative: use webarchive.org - even slower)
- data isn't free to use

One of the problems is that I'm not sure what people expect from an HTML generator output. Complete web pages? Rich text content with generic elements (`<div>`, `<h1>`, etc.)? things that can be displayed on screen (i.e. without relying on external CSS/JS)?

**Comment by Petah** [comment]
Well, if it is acceptable to call a website for this (which I don't think it is), you could just use the API http://loripsum.net/api

**Comment by fzaninotto** [comment]
For results such as the ones from this resource, the generator in the works in #514 is already better.

**Comment by Petah** [comment]
Fair enough I haven't looked into #514. Just FYI the loripsum is customisable: http://loripsum.net/generate.php?p=5&l=long&d=1&a=1&co=1&ul=1&ol=1&dl=1&bq=1&h=1&ac=1&pr=1

**Comment by bwach** [comment]
@fzaninotto @Petah I also could use it and would be happy to pick it up. 

I see it similarly as #514 where we get a piece of html that could simulate ckeditor output for example for content of articles/blocks within cms systems(that's my usecase).

 The main downside of getting remote html @fzaninotto is that it requires internet connection which isn't always the case for me, we can add another generator for it later as well (for example as "webpage" while this one would be "html") what do You think?

**Comment by fzaninotto** [comment]
You're right, depending on a web resource becomes a no-go now that we see that it really bothers users (see #957).

**Comment by fzaninotto** [comment]
New implementation started in #971

**Comment by fzaninotto** [comment]
Fixed in #971
