### ISSUE TITLE
Add data provider for French addresses

### ISSUE THREAD

**Issue by theofidry** [fzaninotto/Faker#505]
Some data providers are lacking for French addresses:
* Complementary data of the “delivery point”: stairs, apartment, floor, at somebody’s house, etc.
* Complementary data on the location: building, residence, etc.
* Distribution service, complementary data on the street location (BP, lieu-dit...).
* Postal or Cedex code (Cedex is not handled).

Sources:
* [Bureau International UPU](http://www.upu.int/fileadmin/documentsFiles/activities/addressingUnit/fraFr.pdf)
* [LaPoste](http://fr.wikipedia.org/wiki/Adresse_postale)

**Comment by fzaninotto** [comment]
Hi @theofidry, there are missing data providers in all languages. If we open one issue for each, this will drown bug or more important feature request issues. If you have a pull request to submit regarding this issue, I'd be glad to merge it, but as such this issue is of low value for the project. I'll close it.
