### ISSUE TITLE
Provider Standards

### ISSUE THREAD

**Issue by BruceLampson** [fzaninotto/Faker#657]
I wanted to write a provider for my country (Nicaragua). After going over a few of the ones already defined; I noticed there are no standards. Many properties were not present in other providers. Is there an initiative in regards to this matter of inconsistency? if not I would love to hear your thoughts on this. :)

**Comment by BruceLampson** [comment]
I think we should add interfaces in order to standardize providers

**Comment by fzaninotto** [comment]
There is no initiative, and I don't think it's necessary. It's already hard enough to find contributors willing to add providers for a certain locale, so it'd be counterproductive to refuse PRs because they don't include all required providers.

Thanks for your suggestion anyway. And I'm looking forward to your Nicaraguayan provider!

**Comment by BruceLampson** [comment]
@fzaninotto Thank you for your quick response. I really love this library its extremely useful but Its very sad to have such level of inconsistency. I strongly believe that adding interfaces would make it easier for future contributor. I'll love to give it try before just saying no to this idea :)
