### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by hackel** [fzaninotto/Faker#870]
It's been almost a year since 1.5 was released.  I was trying to use the dateTimeInInterval formatter when I discovered, after much frustration, that this isn't even included in the latest version.

If you're not ready to release, another thing you could do is change the default branch to stable so that the default docs displayed are for the current stable version people are actually going to use.

Anyway, just thought I would throw this out there.  It's a great, essential project.  Thanks for all that you do!

**Comment by fzaninotto** [comment]
Thanks for the heads up. I know Faker users expect a new release, it's just not as straightforward as you would imagine, because I must document all the changes. 

I'll try to find time for it in the upcoming weeks.

**Comment by hackel** [comment]
Indeed, certainly wasn't meaning to trivialize the process.  If you'd care to point me to some undocumented changes, I can definitely add some.  Thanks again.

**Comment by c33s** [comment]
would also love to see a new tag. 
currently the documentation is out of sync because if you are comming from packagist you land on the master branch and read the docs from there. 
i woundered for a sec. why `dateTimeInInterval` has not worked when i installed `nelmio/alice`.

so it would be good to tag a new release even if the docs are not in sync (just add an info to the doc, that they are not in sync would be enough i think).
