### ISSUE TITLE
Dash Support

### ISSUE THREAD

**Issue by tillkruss** [fzaninotto/Faker#915]
It would be awesome if the Faker documentation would be accessible via [Dash](https://kapeli.com/dash).

**Comment by fzaninotto** [comment]
So many things would be awesome in this world!

**Comment by fzaninotto** [comment]
This issue seems to be getting a lot of attention lately, so maybe I should elaborate a bit on my answer.

First of all, I apologize to @tillkruss if I ever discouraged him to contribute to Faker or any other open-source project. That was not my intention.

My intention was to tell @tillkruss that this issue was a very low quality contribution, albeit with a touch of humour.

Dash is a commercial product. I don't mind when people make money using open-source code that I maintain, but don't ask me to work for free for a company that will benefit from it.

To my defense, let me explain why I found the issue so annoying that I thought that explaining my point would be a waste of time. 

I'm the lead developer / maintainer of several open-source project, either under my own GitHub name ([fzaninotto](https://github.com/fzaninotto)), or under my company's name ([marmelab](https://github.com/marmelab)). These projects add up to more than 30,000 stars. What that means is that I receive several notifications for new issues and PRs *per day* each day of the year. Most of my open-source activity these days is passed triaging these issues. And a good 40% of these issues (my guesstimate) is of low quality. What I mean by that is:

- people asking me to do their job ("How do I use your project to build my startup?")
- people who don't read the documentation (each of my projects has a strong enphasis on documentation)
- people complaining about obscure bugs (that I spend time to try and reproduce), only to realize that the problem is on their side
- people contributing low-quality code (no tests, no documentation, no use case, failing tests)
- people who don't provide context or motivation
- people who don't care to answer my comments on their issue
- people suggesting adding the project to a gazillion other projects, like this issue

Let me give you a few examples:

- https://github.com/marmelab/react-admin/issues/1692
- https://github.com/marmelab/react-admin/issues/1698
- https://github.com/marmelab/ng-admin/issues/1368
- https://github.com/marmelab/ng-admin/issues/1313
- https://github.com/fzaninotto/Faker/pull/1337
- https://github.com/fzaninotto/Faker/pull/1327
- https://github.com/fzaninotto/Faker/pull/1294
- https://github.com/fzaninotto/Faker/pull/1107
- https://github.com/fzaninotto/Faker/issues/1436

I do my best to stay polite and explain to these contributors that to be useful, their contribution requires a bit more work. I write [issue templates](https://github.com/marmelab/react-admin/blob/master/.github/ISSUE_TEMPLATE.md), I provide [CodeSandbox](https://codesandbox.io/s/q7r99p8349) for issue reproduction, I even have [canned answers](https://github.com/marmelab/react-admin/issues/1692#issuecomment-376301168) to be as polite as possible. But sometimes I find the contribution too bad to even bother explaining why it's bad. Or I'm simply out of time, or tired. So I loose my manners.

There are other examples of me not being formal enough, which I am not proud of. I list a few here so people don't throw them at my face:

- https://github.com/marmelab/react-admin/issues/1609#issuecomment-370412888
- https://github.com/marmelab/react-admin/pull/1761#issuecomment-383605491

By the way, why do *I* contribute to open-source software?

I write code for my own needs, or for the needs of my customers. I try as much as possible to open-source this code - because I use a lot of open-source code written by others, and I think it can only work if everyone contributes. I also think that open-sourcing code forces me (and my coworkers) to reach higher quality standards. I open-source code to get free bug fixes from the community, and that partially works. Finally, I invest in open-source to create a brand (the [marmelab](https://marmelab.com/en/showcase) brand), hoping that some companies will like our contributions and become customers. So far, the return on investment of this last purpose has been poor.

If people can use my code for their own needs, I'm glad. But if open-sourcing my work means spending too much time explaining people how to code, I simply think it's not my mission. I lead a company, I have to pay the salaries of many employees at the end of the month, and my time is counted. My priority is *not* to help random people solve their problems with my code. My priority is to try and make my company, marmelab, a strong open-source contributor, without losing money. And this already requires a lot of my (professional and personal) time.

To conclude on this issue, I do my best to be a good open-source citizen. I'm also a human being, so sometimes my answers upset people, and I regret it. If you are such a person, please accept my apologies, and please continue to contribute to open-source projects.

**Comment by tillkruss** [comment]
@fzaninotto: I thought it was funny and en pointe, just to be clear ☮️
