### ISSUE TITLE
Support Propel 2

### ISSUE THREAD

**Issue by alexisvincent** [fzaninotto/Faker#932]
Are there any plans to support Propel2?

**Comment by fzaninotto** [comment]
Not from me, please ask @marcj

**Comment by alexisvincent** [comment]
@marcj ?

**Comment by marcj** [comment]
If I would close feature requests/issues due the fact that I as maintainer have no time to develop it would lead to dramatic clean issue tracker for my projects ;)
However, through closing @fzaninotto signaled he won't have Propel2 support. That's at least the message that arrives me. Closing a feature request (although it's actually a compatibility-fix, [since Propel2 has already been implemented](https://github.com/fzaninotto/Faker/tree/master/src/Faker/ORM/Propel2) in an older version and would need only some little patches like Peer -> TableMap) wouldn't make sense otherwise. That harms contributions massively.

Whatever, I'm not going to contribute that due to time lack. @alexisvincent feel free to give it a try, it's fairly simple to heave it to the current v2 code base. If you have any question, feel [free to join us](https://gitter.im/propelorm/Propel).
