### ISSUE TITLE
dateBetween($format = 'Y-m-d')

### ISSUE THREAD

**Issue by mstnorris** [fzaninotto/Faker#984]
You have `dateTimeBetween` but no simple `dateBetween`.

**Comment by Powerhead13** [comment]
You can simply do 
```
$dt = $faker->dateTimeBetween($startDate = '-30 years', $endDate = 'now');
$date = $dt->format("Y-m-d"); // 1994-09-24
```

**Comment by mstnorris** [comment]
I know that that can be done, but why not a simple method to do that in one line? There are many other methods too but that was just one suggestion.

**Comment by the-noob** [comment]
What's the reason for 'between' in your proposal when you supply just the format?
There is already a [date($format = 'Y-m-d', $max = 'now') ](https://github.com/fzaninotto/Faker#fakerproviderdatetime)

**Comment by fzaninotto** [comment]
Faker is like a pack of Lego™ bricks. I'm amazed by all the wonders you guys manage to build with it, but it doesn't mean that these wonders should be provided out of the box.

So we won't implement this. As @Powerhead13 said, it's a 2-liner.

**Comment by garygreen** [comment]
@fzaninotto @Powerhamster 

Saying your "amazed by us being able to build stuff with it" is totally unnecessary thing to say. It's a pretty reasonable request, `dateBetween` makes a lot of sense - especially when it comes to the `unique()` and other modifiers.

If you do:

```php
$dt = $faker->unique()->dateTimeBetween($startDate = '-30 years', $endDate = 'now');
```

You'll end up with lots of unique date AND times - this is not what you want, you simply want unique dates between a given range. There are ways around it, like generating a random number and adding on those number of days etc, but that's not as explicit and a bit more clunky. Since there already is a `dateTimeBetween` it makes sense to have a corresponding `dateBetween` as well.

**Comment by Oxicode** [comment]
+1 `$date = $this->faker->unique()->dateBetween('now', '+15 days');`

**Comment by bubblemedialtd** [comment]
+1 `$date = $this->faker->unique()->dateBetween('now', '+15 days');`

**Comment by hafezdivandari** [comment]
@fzaninotto Using dateTimeBetween() with unique() is still a issue. please reopen this or suggest a solution.
